### ISSUE TITLE
Remove the attempt to grab `msg` and `message` from exceptions

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/virtualbox-python#107]
Not all exceptions have `.msg` or `.message`. If we don't find either we should just reraise the exception. It clouds tracebacks when we this occurs making it tough for users to know what's going on.

**Comment by noxdafox** [comment]
protip: most of the exception embed the message in their __str__ magic method.

Therefore this is approach is usually preferred:
```
str(error)
```

In the worst case it will fallback to the Python default `object` implementation.
