### ISSUE TITLE
keyboard.put_keys unable to print capitalized english alphabets

### ISSUE THREAD

**Issue by pyvboxtester** [sethmlarson/virtualbox-python#119]
##### ENVIRONMENT

- Operating System: Ubuntu 18.04 x86_64
- Python version: 3.6.7
- VirtualBox version: 5.2.18
- VirtualBox SDK version: Any
- Location where VirtualBox SDK is installed: Any
- pyvbox version: Any
- [x] Happens in latest `master` branch?

##### SUMMARY

keyboard.put_keys unable to print capitalized english alphabets

##### STEPS TO REPRODUCE
session.console.keyboard.put_keys('ABCDEFGHIJKLMNOPQRSTUVWXYZ')

##### EXPECTED RESULTS
ABCDEFGHIJKLMNOPQRSTUVWXYZ

##### ACTUAL RESULTS
AbCdEfGHIJKLMnopqRSTUVwXYZ

**Comment by jricardodeleon** [comment]
Have the same issue, did you get the solution?

**Comment by sethmlarson** [comment]
I'm unable to reproduce this, maybe change your delay time between keys?
