### ISSUE TITLE
Failed to find attribute guest

### ISSUE THREAD

**Issue by applejuiceyy** [sethmlarson/virtualbox-python#120]
##### ENVIRONMENT

- Operating System: Windows 7 64bits
- Python version: 3.6.4
- VirtualBox version: 5.2.6 r120293 (Qt5.6.2)
- VirtualBox SDK version: 6.0.2-128162
- Location where VirtualBox SDK is installed: 
- pyvbox version: 1.3.2
- [x] Happens in latest `master` branch?

##### SUMMARY
Can't find attribute guest in virtualbox.library_ext.console.IConsole object, it was working before, now it ism't working anymore

##### STEPS TO REPRODUCE
Follow examples (with necessary changes)

##### EXPECTED RESULTS
Run normally

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    gs = session.console.guest.create_session('runner', '')
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\virtualbox\library.py", line 14536, in guest
    ret = self._get_attr("guest")
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\virtualbox\library_base.py", line 165, in _get_attr
    attr = self._search_attr(name, prefix='get')
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\virtualbox\library_base.py", line 161, in _search_attr
    raise AttributeError("Failed to find attribute %s in %s" % (name, self))
AttributeError: Failed to find attribute guest in <virtualbox.library_ext.console.IConsole object at 0x03C2B690>
```

**Comment by sk3lk0** [comment]
try it https://archblog.pro/?p=100

**Comment by sethmlarson** [comment]
Are you using a different Virtualbox and Virtualbox SDK versions? Maybe that's the issue, try updating the SDK.

**Comment by sethmlarson** [comment]
I no [longer have time to maintain this library](https://github.com/sethmlarson/virtualbox-python/commit/36cb7d34dac4763e250ca0c44128a40d93d9fce5), so am closing this issue.
