### ISSUE TITLE
Update library.py with vbox 6.0.x xidl

### ISSUE THREAD

**Issue by apatrushev** [sethmlarson/virtualbox-python#123]
##### ENVIRONMENT
- Operating System: Any
- Python version: Any
- VirtualBox version: 6.0.4
- VirtualBox SDK version: 6.0.4
- Location where VirtualBox SDK is installed: any
- pyvbox version: 1.3.2
- [v] Happens in latest `master` branch?

##### SUMMARY
VirtualBox 6.0 contains new constants in enums, for example VirtualSystemDescriptionType. This breaks some api call, for example working with appliance (unknown values on conversion from numeric to enums)

**Comment by sethmlarson** [comment]
I'm working on this currently.

**Comment by sethmlarson** [comment]
Just released support for 6.0.x in virtualbox==2.0.0 (or pyvbox==2.0.0)
