### ISSUE TITLE
Finding a VM's VDRE Configuration

### ISSUE THREAD

**Issue by eohrnberger** [sethmlarson/virtualbox-python#135]
Hi,
I've got pyvbox and vboxapi installed and working, finding the collection of VMs (vobx.machines) and the collection of hard disks (vbox.hard_disks).  

My question is how do I access the VDRE parameters of a vbox.machines instance?  I'm specifically looking for the port number.

Thanks in advance.

**Comment by sethmlarson** [comment]
I believe you can do `machine.vrde_server_info.port`.

**Comment by eohrnberger** [comment]
Hi,
    Thanks for responding.  I've looked into this further:

machine.vrde_server has the following properties:
allow_multi_connection
auth_library
auth_timeout
auth_type
enabled
reuse_single_connection
vrde_ext_pack
vrde_properties

machine.vrde_server.vrde_properties has strings in a list:
00: 'TCP/Ports'
01: 'TCP/Address'
02: 'VideoChannel/Enabled'
03: "VideoChannel/Quality'
04: VideoChanel/DownscaleProtection'
05:'Client/DisableDisplay'
06:'Client/DisableInput'
07:'Client/DisableAudio'
08:'Client/DisableUSB'
09:'Client/DisableClipboard'
10:'Client/DisableUpstreamAudio'
11:'Client/DisableRDPDR'
12:'H3Redirect/Enabled'
13:'Security'Method'
14:'Security/ServerCirtificate'
15:'Security/ServerPrivateKey'
16:'Security/CACertificates'
17:'Audio/RateCorrectionMode'
18:'Audio/LogPath'

Where would the values for these configuration parameters be found in the interface?

**Comment by sethmlarson** [comment]
Try `machine.vrde_server.get_vrde_property("TCP/Ports")`. You should be able to put any of those keys into that getter.

**Comment by eohrnberger** [comment]
Oh hot dam!  Thanks!
(I have to admit, I'm just starting out with python)  :)

**Comment by sethmlarson** [comment]
No problem! This library, although it says it's 'Pythonic', on the tin, it's not actually very 'Pythonic' in many ways. This is because it follows the VirtualBox API strictly for almost all functionality, like the piece you're using. :)

Hope you get some good use out of the library and good luck with learning Python!
