### ISSUE TITLE
Error when setting the AutostopType mode.

### ISSUE THREAD

**Issue by davesliu** [sethmlarson/virtualbox-python#139]
Hello,

I want to shutdown the virtual machine with save_state mode but failed with below code.

self.machine.autostop_type(virtualbox.library.AutostopType.save_state)

it said that TypeError: 'AutostopType' object is not callable

but I use a similar enumerate call for 
self.machine.lock_machine(self.session, virtualbox.library.LockType.write)
and it will not report any error.

So could anyone figure out the root cause of 'AutostopType error?

Thanks in advance.

##### ENVIRONMENT

- Operating System:  win10
- Python version:  3.7
- VirtualBox version: 6.0. 8
- VirtualBox SDK version:6.1.2
- Location where VirtualBox SDK is installed: the installer folder
- virtualbox-python / pyvbox version: 2.0.0

**Comment by sethmlarson** [comment]
`machine.autostop_type` is a property, not a function. To set it do this: `...machine.autostop_type = AutostopType.save_state`.

**Comment by davesliu** [comment]
thanks for your help :-)

**Comment by davesliu** [comment]
@sethmlarson 
I want to save the current virtual machine snapshot when power off.
When I use your command, it still pop out errors as shown in below log. Does it mean that we can't set the save_state when virtual machine is running? If yes,  what's the pre-condition of setting the save_state mode?

self.machine.autostop_type = virtualbox.library.AutostopType.save_state

  File "xx\AppData\Local\Programs\Python\Python37\lib\site-packages\virtualbox\library.py", line 12498, in autostop_type
    return self._set_attr("autostopType", value)
  File "xx\AppData\Local\Programs\Python\Python37\lib\site-packages\virtualbox\library_base.py", line 184, in _set_attr
    return setattr(self._i, name, value)
  File "xx\AppData\Local\Programs\Python\Python37\lib\site-packages\vboxapi\__init__.py", line 193, in _CustomSetAttr
    return _g_dCOMForward['setattr'](self, ComifyName(sAttr), oValue)
  File "xx\AppData\Local\Programs\Python\Python37\lib\site-packages\win32com\client\__init__.py", line 482, in __setattr__
    self._oleobj_.Invoke(*(args + (value,) + defArgs))
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'MachineWrap', 'The machine is not mutable, saved or running (state is Running)', None, 0, -2135228414), None)
