### ISSUE TITLE
More gentle alternative to session.console.power_down()

### ISSUE THREAD

**Issue by pmarini** [sethmlarson/virtualbox-python#140]
Is there a way to shutdown guests in a more gentle way than `session.console.power_down()` does?
I'm thinking about the equivalent of 
```
.\VBoxManage.exe controlvm <vm name> acpipowerbutton
```
that is to to send the guest the power off signal, and let the power off utilities do their work there.

If provided with some guidelines I may try to implement the enhancement myself.

Thanks!

**Comment by sethmlarson** [comment]
Have you tried `...console.sleep_button()`? Let me know if it works or not.

**Comment by pmarini** [comment]
Hi, 

Thanks for the quick reply. 

It looks like `session.console.sleep_button()` doesn't power off the guest. I don't know exactly what it does but it doesn't trigger a proper shutdown, as 

```
.\VBoxManage.exe controlvm <vm name> acpipowerbutton
```

does.

**Comment by sethmlarson** [comment]
What about `.power_button()`?

**Comment by pmarini** [comment]
Yes it `.power_button()` does the job. Thanks!
