### ISSUE TITLE
How to press Enter key on running VM?

### ISSUE THREAD

**Issue by Aviv-Cyber** [sethmlarson/virtualbox-python#142]
##### SUMMARY
im trying to use the keyboard on the linux VM,
pressing Enter, Space, and other esssentials keys.

The VM starts, it asks for my useraname, the python code inserts it,
then i want to hit enter in order the insert the password, but i just cant figure out how to press the Enter key...

**Comment by sethmlarson** [comment]
Have you tried `put_keys(["ENTER"])`?

**Comment by Aviv-Cyber** [comment]
Thanks it worked
But why the [ ] is necessary?

**Comment by Aviv-Cyber** [comment]
[image: image.png]

when i wrote the following code, the machine is just stuck on this grey
screen, how would you recommend me to login into the machine using your
code ?

**Comment by Karol-G** [comment]
Hi,

I also want to send key strokes to my VM. However there is no documentation I could find on how to do so. I tried `session.console.keyboard.put_keys("Hello, world!")` but this just throws the error: 
```
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'SessionWrap', 'The session is not locked (session state: Unlocked)', None, 0, -2147418113), None)
``` 
Could you maybe give a minimal example on how to send keystrokes?

Best
Karol

**Comment by Aviv-Cyber** [comment]
Hi Karol,
Im currently at work but I have figured out how to do it, please remind me
in 2 and a half hours from now and I will share my knowledge with you.

**Comment by Karol-G** [comment]
I think I figured it out too:

```
vbox = virtualbox.VirtualBox()
machine = vbox.find_machine("Ubuntu 20")  # Find a running VM named "Ubuntu 20"
session = machine.create_session()  # Connect to the VM
session.console.keyboard.put_keys("Hello, world!")  # Send the keys "Hello, world!" to the VM
```

That worked for me.

**Comment by Aviv-Cyber** [comment]
Oh great,

It's good we both find the same subject interesting
