### ISSUE TITLE
Cant set VRAM size or change graphics display adapter

### ISSUE THREAD

**Issue by OctoNezd** [sethmlarson/virtualbox-python#146]
##### ENVIRONMENT

- Operating System: Windows 10 2004
- Python version: 3.8.3
- VirtualBox version: 6.1.12 r139181
- VirtualBox SDK version: 6.1.12-139181
- Location where VirtualBox SDK is installed: 
- virtualbox-python / pyvbox version:
- [x] Happens in latest `master` branch?

##### SUMMARY

I can't set the vram_size or graphics_controller type on any machine

##### STEPS TO REPRODUCE

Try setting vram_size and/or graphics_controller_type:
```
session.machine.graphics_controller_type = virtualbox.library.GraphicsControllerType.v_box_svga
session.machine.vram_size = 128
```

##### ACTUAL RESULTS

```
  File "main.py", line 181, in vbox_run
    session.machine.graphics_controller_type = virtualbox.library.GraphicsControllerType.v_box_svga
  File "C:\Users\octo\PycharmProjects\mrvnpebuilder\venv\lib\site-packages\virtualbox\library.py", line 11691, in graphics_controller_type
    return self._set_attr("graphicsControllerType", value)
  File "C:\Users\octo\PycharmProjects\mrvnpebuilder\venv\lib\site-packages\virtualbox\library_base.py", line 178, in _set_attr
    attr = self._search_attr(name, prefix='set')
  File "C:\Users\octo\PycharmProjects\mrvnpebuilder\venv\lib\site-packages\virtualbox\library_base.py", line 167, in _search_attr
    raise AttributeError("Failed to find attribute %s in %s" % (name, self))
AttributeError: Failed to find attribute graphicsControllerType in Test VM for PE pe_test
```

**Comment by OctoNezd** [comment]
Apparently in some version graphicsAdapter attribute was added and `vram_size` with `graphics_controller_type` were removed, cause I can find them in sdk .pdf documentation only on IGraphicsAdapter class

**Comment by sethmlarson** [comment]
Maybe this project needs a regeneration, I'll take a look.

**Comment by sethmlarson** [comment]
I no [longer have time to maintain this library](https://github.com/sethmlarson/virtualbox-python/commit/36cb7d34dac4763e250ca0c44128a40d93d9fce5), so am closing this issue.
