### ISSUE TITLE
Get IP from running virtualbox machine

### ISSUE THREAD

**Issue by akozyreva** [sethmlarson/virtualbox-python#159]
##### ENVIRONMENT

- Operating System: Linux 5.12.9-1-MANJARO x86_64 21.0.7 Ornara
- Python version: Python 3.9.5
- VirtualBox version: 6.1
- VirtualBox SDK version: 6.1.22
- Location where VirtualBox SDK is installed: /home/akozyreva/projects/ftp-testing/
- virtualbox-python / pyvbox version: 2.1.1
- [x] Happens in latest `master` branch?

##### SUMMARY
I have installed Ubuntu Server in Virtualbox. I can run this machine, using code from documentation.
```
import virtualbox
vbox = virtualbox.VirtualBox()
session = virtualbox.Session()

print([m.name for m in vbox.machines])
machine = vbox.find_machine('Ubuntu Server')
proc = machine.launch_vm_process(session, "gui", [])
proc.wait_for_completion()
```
Then I need to retrieve somehow public IP from that machine. Inside of virtualbox I can run `ifconfig` and get public IP. How can I do it via `virtualbox-python` package?

**Comment by alainpannetier** [comment]
Hum, that's why I came to the SDK today. :+1: 
I don't know yet but, assuming you'd have installed the guest additions, the following would work

``` bash
vboxmanage guestproperty enumerate "Alpine 01" | grep VirtualBox/GuestInfo/Net/1/V4/IP
```
Let's see if there is a _guestproperty_ object somewhere.

**Comment by sethmlarson** [comment]
Closing this, thanks @alainpannetier!
