### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by svenons** [sethmlarson/virtualbox-python#163]
##### ENVIRONMENT

- Operating System: Windows 10
- Python version: 3.10.7
- VirtualBox version: 6.1.38

##### SUMMARY
Can't install vboxapisetup because setup by python file is depreceated and gives error that it can't write on the necessary directory. Tried powershell, tried disabling Windows protection.

**Comment by cdorsman** [comment]
Have you tried installing with CommandPrompt with administrative rights?
