### ISSUE TITLE
Is there any more detail usage of this package?

### ISSUE THREAD

**Issue by web4zn** [sethmlarson/virtualbox-python#164]
I have encounted many problem. But I did not find any detail document for this package. Is there any have github project using this package?

I am now stuck by some functions like power_down() wont wait_for_completion.

And I still want to learn how to use event.

**Comment by x007007007** [comment]
Is this project still maintained?

**Comment by sethmlarson** [comment]
I no [longer have time to maintain this library](https://github.com/sethmlarson/virtualbox-python/commit/36cb7d34dac4763e250ca0c44128a40d93d9fce5), so am closing this issue.
