### ISSUE TITLE
Win10 create machine not work, and give me execptions

### ISSUE THREAD

**Issue by x007007007** [sethmlarson/virtualbox-python#166]
https://stackoverflow.com/questions/75890104/virtualbox-api-ivirtualboxcreatemachine-causing-exceptions

##### ENVIRONMENT

Virtualbox 
SDK 
pywin32 306
vboxapi 1.0
virtualbox 2.1.1
- Operating System:  Windows 10
- Python version: 3.11
- VirtualBox version: 7.0.8
- VirtualBox SDK version: 7.0.8 installed
- Location where VirtualBox SDK is installed: C:\Program Files\Oracle\VirtualBox\sdk
- virtualbox-python / pyvbox version: 2.1.1
- [ ] Happens in latest `master` branch?

**Comment by sethmlarson** [comment]
I no [longer have time to maintain this library](https://github.com/sethmlarson/virtualbox-python/commit/36cb7d34dac4763e250ca0c44128a40d93d9fce5), so am closing this issue.

**Comment by guriWiz** [comment]
The virtual box API version 7.0 doesn't work with python **3.11.0**. It only supports **3.10** version so you should switch back to that version and try again.

**Comment by 0nelight** [comment]
Unfortunately, the "createMachine" interface has changed from VirtualBox 6 to 7.
This Repo was made for the Version `vbox_version = "6.1.16"` as written in virtualbox/library.py.

You can change library.py to the following to make it work again. (but I don't know what else is broken too):
```python
machine = self._call(
    "createMachine", in_p=[settings_file, name, groups, os_type_id, flags, "", "", ""]
)
```

Check out https://download.virtualbox.org/virtualbox/ and then the SDK Documentation in the respective Version-Folders.

**Comment by guriWiz** [comment]
@0nelight I have been testing each method to see which one's are broken. I will take a look at `createMachine` method too.
