### ISSUE TITLE
Extend test suite to support Python 3.x

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/virtualbox-python#64]
##### ENVIRONMENT

- Operating System: Any
- Python version: 3.x
- VirtualBox version: Any
- VirtualBox SDK version: Any
- pyvbox version: Any
- [x] Happens in latest `master` branch?

##### SUMMARY
Can't run the test suite in Python 3.x

##### EXPECTED RESULTS
Runs test suite

##### ACTUAL RESULTS
Errors with NameErrors due to usage of `basestring`.

**Comment by WheelNet** [comment]
I recently opened a question on stackoverflow about there being issues with python 3. vboxapi. Big mess. 

@SethMichaelLarson Are you the brave soul who has self-assigned this mess?

**Comment by WheelNet** [comment]
Oh wow. I could do the code if you do the tests.

**Comment by WheelNet** [comment]
Sigh. I can't commit to that at this time. I already have so much work.

**Comment by WheelNet** [comment]
https://stackoverflow.com/questions/44477318/is-it-possible-to-use-the-python3-bindings-for-virtualbox?noredirect=1#comment75949954_44477318

**Comment by WheelNet** [comment]
Is this the right place for this (as making tests work implies fixing a lot of bugs), or should I create a separate issue
