### ISSUE TITLE
Restructure Project for Proper Auto-completion

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/virtualbox-python#92]
This project has problems with auto-complete. This is something for 2.0.0 as it would require complete re-work of structure.

**Comment by SethMichaelLarson** [comment]
The problems boil down to these two places:
- Extensions in library_ext aren't registered by most IDE auto-completion helpers.
- Enumeration values aren't registered by IDEs. Implementing #86 would fix this.

**Comment by SethMichaelLarson** [comment]
This would also require switching to a better docstring format for type hinting. ie:

#### Before
```python
def read_log(self, idx, offset size):
    """
    ...

    in idx of type int
        Which log file to read. 0=current log file
    
    in offset of type int
        Offset in the log file.

    in size of type int
        Chunk size to read in the log file.

    return data of type str
        Data read from the log file
    """
```

#### After
```python
def read_log(self, idx, offset size):
    """
    ...

    :param idx: Which log file to read. 0=current log file
    :param offset: Offset in the log file.
    :param size: Chunk size to read in the log file.
    :type idx: int
    :type offset: int
    :type size: int
    :rtype: str
    :returns: Data read from the log file
    """
```

These hints will show up much nicer in an IDE, especially with a docstring inspector. Possibly could help with auto-generated documentation as well.

**Comment by SethMichaelLarson** [comment]
Would love to have your help with this @mjdorma when you have time. :)

**Comment by mjdorma** [comment]
Good idea wrt to marking up the variables. That should be within the scope of the current builder :).

**Comment by SethMichaelLarson** [comment]
That's what I was hoping! It's so much easier to stand on the shoulders of giants ;)
