### ISSUE TITLE
Change the name of the project to `virtualbox`?

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/virtualbox-python#93]
Oracle doesn't seem to want to take the name on PyPI, we would get a lot more installs this way.
We can keep deploying to `pyvbox` and `virtualbox` at the same time to maintain backwards compatbility.

**Comment by mjdorma** [comment]
I'm happy to do a full transition and drop pyvbox. I suppose if there are naming issues in the future things can be unwound.

**Comment by SethMichaelLarson** [comment]
We could also upload a stub package to `pyvbox` that just raises an error saying that we upgraded and they should either pin their version or switch to `virtualbox`. I think we should make the `virtualbox` package be only 2.0.0

**Comment by angryjk** [comment]
sorry for offtop, but have an urgent question: how to gs.execute('ipconfig --help') - command? Asking because that space in after command is causing err: 1, u'', u"''ipconfig' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

**Comment by angryjk** [comment]
have made some investigation and understand that space between comand and key is causing such problem!!! Is anyone know how to make it working? once more time sorry for offtop

**Comment by SethMichaelLarson** [comment]
@angryjk Could you open a separate issue?
